#include "Utility/clear.common.hlsl"

#define RESOURCE_DIMENSION_TEXTURE_1D		(0)
#define RESOURCE_DIMENSION_TEXTURE_1D_ARRAY	(1)
#define RESOURCE_DIMENSION_TEXTURE_2D		(2)
#define RESOURCE_DIMENSION_TEXTURE_2D_ARRAY	(3)
#define RESOURCE_DIMENSION_TEXTURE_3D		(4)

#ifndef CLEAR_TEXTURE_CHANNELS_COUNT
#define CLEAR_TEXTURE_CHANNELS_COUNT		(4)
#endif

#if CLEAR_TEXTURE_CHANNELS_COUNT <= 0 || CLEAR_TEXTURE_CHANNELS_COUNT > 4
#error "Invalid CLEAR_TEXTURE_CHANNELS_COUNT"
#endif

#define CLEAR_CONCATENATE_RW(TextureType)	RWTexture ## TextureType

#ifndef CLEAR_SPIRV_FORMAT
#define CLEAR_SPIRV_FORMAT					SPIRV_FORMAT_RGBA8
#endif

#ifndef CLEAR_TEXTURE_TYPE
#define CLEAR_TEXTURE_TYPE					RESOURCE_DIMENSION_TEXTURE2D
#endif

#if CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_1D
#define CLEAR_TEXTURE_TYPE_TOKEN			1D
#elif CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_1D_ARRAY
#define CLEAR_TEXTURE_TYPE_TOKEN			1DArray
#elif CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_2D
#define CLEAR_TEXTURE_TYPE_TOKEN			2D
#elif CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_2D_ARRAY
#define CLEAR_TEXTURE_TYPE_TOKEN			2DArray
#elif CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_3D
#define CLEAR_TEXTURE_TYPE_TOKEN			3D
#endif

#ifndef CLEAR_TEXTURE_TYPE_RW
#define CLEAR_TEXTURE_TYPE_RW				CLEAR_CONCATENATE_RW(CLEAR_TEXTURE_TYPE_TOKEN)
#endif

#define CLEAR_TEXTURE_FORMAT				float##CLEAR_TEXTURE_CHANNELS_COUNT

#if CLEAR_TEXTURE_CHANNELS_COUNT == 2		
#define CLEAR_TEXTURE_CHANNEL_SWIZZLE		xy
#elif CLEAR_TEXTURE_CHANNELS_COUNT == 3		
#define CLEAR_TEXTURE_CHANNEL_SWIZZLE		xyz
#elif CLEAR_TEXTURE_CHANNELS_COUNT == 4		
#define CLEAR_TEXTURE_CHANNEL_SWIZZLE		xyzw
#else										
#define CLEAR_TEXTURE_CHANNEL_SWIZZLE		x
#endif

CONSTANT_BUFFER(ClearConstants,														ClearConstantBuffer,	0, 0);
RW_RESOURCE(CLEAR_TEXTURE_TYPE_RW,	CLEAR_TEXTURE_FORMAT,	CLEAR_SPIRV_FORMAT,		OutTexture,				0, 0);

#if CLEAR_TEXTURE_TYPE == CLEAR_TEXTURE_TYPE_TEXTURE1D
#define CLEAR_ANY( Value )					(Value)
#else
#define CLEAR_ANY( Value )					(any(Value))
#endif


[numthreads(THREAD_GROUP_COUNT_X, THREAD_GROUP_COUNT_Y, THREAD_GROUP_COUNT_Z)]
void ShaderCompute(uint3 DispatchThreadID : SV_DispatchThreadID)
{
#if CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_1D
	uint  Pixel			= DispatchThreadID.x;
	uint  Size			= ClearConstantBuffer.ClearSize.x;
#elif CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_1D_ARRAY || CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_2D
	uint2 Pixel			= DispatchThreadID.xy;
	uint2 Size			= ClearConstantBuffer.ClearSize.xy;
#else // CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_2D_ARRAY || CLEAR_TEXTURE_TYPE == RESOURCE_DIMENSION_TEXTURE_3D
	uint3 Pixel			= DispatchThreadID.xyz;
	uint3 Size			= ClearConstantBuffer.ClearSize.xyz;
#endif

	if (CLEAR_ANY(Pixel >= Size))
		return;

	OutTexture[Pixel] = ClearConstantBuffer.ClearValue.CLEAR_TEXTURE_CHANNEL_SWIZZLE;
}
